angular 9
worldskills/worldskills-organizations pull request #2
Opened 2020-07-14 17:50 UTC by RajeevSiewnath

2020-07-27 15:19 UTC, gbervik commented on src/app/contacts/contacts.component.ts
> +      this.peopleService.subject.subscribe(people => (this.people = people.people)),
This list could get quite long, especially for the larger Members. In the old UI we had a search form here. Could we do something similar in the angular 9 version?

2020-07-27 15:30 UTC, gbervik commented on src/app/organization/organization.component.html
> +      </ng-container>
In the old UI we had a note here. Could we add that back in please?

![image](https://user-images.githubusercontent.com/4145894/88560660-c698b580-d071-11ea-8729-15e8f9201e82.png)

2020-07-29 07:50 UTC, RajeevSiewnath commented on src/app/contacts/contacts.component.ts
> +      this.peopleService.subject.subscribe(people => (this.people = people.people)),
Yeah for sure, I can make the same async search function as I used in one of the other pages

2020-07-29 07:52 UTC, RajeevSiewnath commented
> I noticed when testing that the notifications persist until manually dismissed. In our AngularJS versions of the applications the notifications disappear after short of time. What are your thoughts on that? On the one hand it can be annoying if the page jumps up every time a notification disappears, but on the other it can get annoying to manually dismiss them.
> 
> ![image](https://user-images.githubusercontent.com/4145894/88562581-34de7780-d074-11ea-944c-99326fb204af.png)

Yeah  it makes sense to have a timeout, and even like an animated slide up (to prevent heavy jumping). This would convenient to add in the library. Also the functions to actually add these messages are a bit cumbersome, so it would also be a good opportunity to simplify that at the same time.

2020-07-29 07:52 UTC, RajeevSiewnath commented on src/app/organization/organization.component.html
> +      </ng-container>
Sure thing!

2020-07-29 08:10 UTC, RajeevSiewnath commented on src/app/contacts/contacts.component.ts
> +      this.peopleService.subject.subscribe(people => (this.people = people.people)),
Actually, maybe even make a library component out of it

2020-08-06 11:09 UTC, fabian commented
Will wait with my review until Adam's point have been addressed.

2020-08-06 12:16 UTC, RajeevSiewnath commented
That’s good. Also I noticed some slight other bugs, but I’ll first finish the events app. Should be anyway now

> On 6. Aug 2020, at 14.10, Fabian Vogler <notifications@github.com> wrote:
> 
> 
> Will wait with my review until Adam's point have been addressed.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/worldskills/worldskills-organizations/pull/2#issuecomment-669864112>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABSDHZGH37RUIY7V44MNLPLR7KFQTANCNFSM4OZX7ZFQ>.
>

2020-09-10 14:19 UTC, gbervik requested changes
Looks good Rajeev. 

The notifications still persist at the top of the page, but it's fine to take care of that later.

A few small things to fix where optional fields are mandatory:
- organization has website as mandatory but should be optional
- addresses Line 2, 3, and 4 are mandatory but they should be optional
- website description is mandatory but should be optional

2020-09-10 15:24 UTC, RajeevSiewnath commented
@gbervik the api disagrees with you regarding the website being optional :D 

![Screenshot 2020-09-10 at 18 16 16](https://user-images.githubusercontent.com/6566884/92752699-d524fd00-f391-11ea-9ff8-113802e3964c.png)

Also for the website description, the API does not agree

![Screenshot 2020-09-10 at 18 23 23](https://user-images.githubusercontent.com/6566884/92753726-d60a5e80-f392-11ea-9282-edcbc525850c.png)

I made them now all optional in the UI, so you can change that now in the API

2020-09-10 15:31 UTC, gbervik commented
> @gbervik the api disagrees with you regarding the website being optional :D
>
> Also for the website description, the API does not agree
> 
> I made them now all optional in the UI, so you can change that now in the API

Oops! 😆  
Ok, I'll change that in the API

2020-09-10 16:25 UTC, gbervik commented
Ok, I've fixed the second error. 

The first one looks like it's a problem when editing the website for an existing organisation. In that case it's doing a PUT to update the existing website

![image](https://user-images.githubusercontent.com/4145894/92762186-afb9e280-f3d5-11ea-9508-bc1bb50f750e.png)

When trying to create a new organisation for a Member it's failing with this in the console:

![image](https://user-images.githubusercontent.com/4145894/92762456-f576ab00-f3d5-11ea-9948-4e6051b016bd.png)

and it's showing this error which I can't dismiss:

![image](https://user-images.githubusercontent.com/4145894/92762533-09baa800-f3d6-11ea-955c-adb119ed9e4d.png)

2020-09-11 09:03 UTC, RajeevSiewnath commented
Hmmm do you have the service running on your localhost? And how are the CROS policies set up? This does not necessarily look like an app error, but rather a server misconfiguration. We could telco later today to go through it?

2020-09-11 10:59 UTC, gbervik commented
Yep, I was running it on localhost. Everything else seemed to be working ok. 

I tried it on the newly resurrected org.worldskills.show and it creates a new organization ok without a website URL.

Happy to chat when you're back online

2020-09-13 14:28 UTC, RajeevSiewnath commented
member organization website should be fixed now. the website field is optional and the app will call the appropriate endpoints when creating, updating or deleting the website.

2020-09-14 02:56 UTC, gbervik approved these changes

2020-12-02 13:55 UTC, TehWazzard approved these changes

2020-12-03 08:27 UTC, TehWazzard commented
The last 2 conflict files don't seem to exist on in the new branch.

2020-12-03 08:32 UTC, TehWazzard commented
Looks like the files we added to support the .dev branch broke the pull request. fixed now,

2020-12-03 10:00 UTC, merged